FROM scratch

ARG IMAGE_TAG=latest

FROM liberoadmin/reviewer_client_webpack:$IMAGE_TAG

MAINTAINER eLife Reviewer Product Team <reviewer-product@elifesciences.org>
WORKDIR /opt

COPY deployment/nginx.conf /etc/nginx/nginx.conf
RUN mv dist/ /usr/share/nginx/html

EXPOSE 80

HEALTHCHECK --interval=1m --timeout=1s \
	CMD curl -f http://localhost/index.html || exit 1
