ARG image_tag=latest

FROM liberoadmin/reviewer_client_webpack:${image_tag} AS built
FROM nginx:1-alpine

MAINTAINER eLife Reviewer Product Team <reviewer-product@elifesciences.org>
WORKDIR /opt

COPY deployment/nginx.conf /etc/nginx/nginx.conf
COPY --from=built /opt/dist/ /usr/share/nginx/html

EXPOSE 80

HEALTHCHECK --interval=1m --timeout=1s \
	CMD curl -f http://localhost/index.html || exit 1
