ARG IMAGE_TAG=latest

FROM liberoadmin/reviewer_client_packages:$IMAGE_TAG

WORKDIR /opt

COPY globals.d.ts .
COPY index.html .
COPY index.tsx .

COPY test-utils/ test-utils/
COPY jest.config.js
COPY tsconfig.json .

COPY webpack/ webpack.
COPY webpack.config.js
COPY webpack.parts.js

COPY src/ ./src/

RUN yarn build
