ARG image_tag=latest

FROM libero/reviewer_client_packages:${image_tag}

WORKDIR /app

COPY globals.d.ts index.html index.tsx .babelrc .eslintrc.js .eslintignore webpack.parts.js jest.config.js tsconfig.json webpack.config.js ./

COPY test-utils/ test-utils/
COPY webpack/ webpack/
COPY src/ ./src/
COPY .storybook/ ./.storybook

RUN yarn build && yarn build-storybook
