ARG image_tag=latest

FROM libero/reviewer_audit_packages:${image_tag} AS audit_packages

FROM node:10-alpine
MAINTAINER eLife Reviewer Product Team <reviewer-product@elifesciences.org>

WORKDIR /app

COPY --from=audit_packages /app/node_modules/ ./node_modules/

COPY  tsconfig.build.json \
      tsconfig.json \
      tslint.json \
      jest.config.js \
      package.json \
      ./

COPY src/ ./src/

RUN yarn build
