FROM liberoadmin/reviewer_server_typescript:latest

MAINTAINER eLife Reviewer Product Team <reviewer-product@elifesciences.org>

WORKDIR /opt

EXPOSE 3000

HEALTHCHECK --interval=1m --timeout=1s \
	CMD curl -f http://localhost:3000/health || exit 1

CMD ["node", "dist/main.js"]

