ARG image_tag=latest

FROM liberoadmin/reviewer_continuum-auth_packages:${image_tag} AS auth_packages

FROM node:10-alpine
MAINTAINER eLife Reviewer Product Team <reviewer-product@elifesciences.org>

WORKDIR /app

COPY --from=auth_packages /app/node_modules/ ./node_modules/

COPY  tsconfig.build.json \
      tsconfig.json \
      tslint.json \
      package.json \
      ./

COPY src/ ./src/

RUN yarn build
